// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

error UNACCEPTABLE_PAYMENT();
error INSUFFICIENT_AMOUNT();
error TRANSACTION_FAILED();
error NONCE_ALREADY_USED();
error SIGNATURE_EXPIRED();
error INVALID_SIGNATURE();
error ZERO_ADDRESS_NOT_ALLOWED();
error ONLY_TICKET_LAUNCHPAD();
error SEAT_ALREADY_CLAIMED();
